/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LotteryLottoRoundImport } from './routes/lottery/lotto/$round'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LotteryLottoRoundRoute = LotteryLottoRoundImport.update({
  id: '/lottery/lotto/$round',
  path: '/lottery/lotto/$round',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/lottery/lotto/$round': {
      id: '/lottery/lotto/$round'
      path: '/lottery/lotto/$round'
      fullPath: '/lottery/lotto/$round'
      preLoaderRoute: typeof LotteryLottoRoundImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lottery/lotto/$round': typeof LotteryLottoRoundRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lottery/lotto/$round': typeof LotteryLottoRoundRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/lottery/lotto/$round': typeof LotteryLottoRoundRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lottery/lotto/$round'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lottery/lotto/$round'
  id: '__root__' | '/' | '/lottery/lotto/$round'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LotteryLottoRoundRoute: typeof LotteryLottoRoundRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LotteryLottoRoundRoute: LotteryLottoRoundRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/lottery/lotto/$round"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/lottery/lotto/$round": {
      "filePath": "lottery/lotto/$round.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
