/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as GamesLotteryLottoIndexImport } from './routes/games/lottery/lotto/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GamesLotteryLottoIndexRoute = GamesLotteryLottoIndexImport.update({
  id: '/games/lottery/lotto/',
  path: '/games/lottery/lotto/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/games/lottery/lotto/': {
      id: '/games/lottery/lotto/'
      path: '/games/lottery/lotto'
      fullPath: '/games/lottery/lotto'
      preLoaderRoute: typeof GamesLotteryLottoIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/lottery/lotto': typeof GamesLotteryLottoIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/lottery/lotto': typeof GamesLotteryLottoIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/games/lottery/lotto/': typeof GamesLotteryLottoIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games/lottery/lotto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games/lottery/lotto'
  id: '__root__' | '/' | '/games/lottery/lotto/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesLotteryLottoIndexRoute: typeof GamesLotteryLottoIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesLotteryLottoIndexRoute: GamesLotteryLottoIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/games/lottery/lotto/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/games/lottery/lotto/": {
      "filePath": "games/lottery/lotto/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
