/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesLotteryLottoIndexRouteImport } from './routes/games/lottery/lotto/index'
import { Route as GamesLotteryLottoRoundRouteImport } from './routes/games/lottery/lotto/$round'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesLotteryLottoIndexRoute = GamesLotteryLottoIndexRouteImport.update({
  id: '/games/lottery/lotto/',
  path: '/games/lottery/lotto/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesLotteryLottoRoundRoute = GamesLotteryLottoRoundRouteImport.update({
  id: '/games/lottery/lotto/$round',
  path: '/games/lottery/lotto/$round',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/lottery/lotto/$round': typeof GamesLotteryLottoRoundRoute
  '/games/lottery/lotto': typeof GamesLotteryLottoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/lottery/lotto/$round': typeof GamesLotteryLottoRoundRoute
  '/games/lottery/lotto': typeof GamesLotteryLottoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/lottery/lotto/$round': typeof GamesLotteryLottoRoundRoute
  '/games/lottery/lotto/': typeof GamesLotteryLottoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games/lottery/lotto/$round' | '/games/lottery/lotto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games/lottery/lotto/$round' | '/games/lottery/lotto'
  id: '__root__' | '/' | '/games/lottery/lotto/$round' | '/games/lottery/lotto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesLotteryLottoRoundRoute: typeof GamesLotteryLottoRoundRoute
  GamesLotteryLottoIndexRoute: typeof GamesLotteryLottoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/lottery/lotto/': {
      id: '/games/lottery/lotto/'
      path: '/games/lottery/lotto'
      fullPath: '/games/lottery/lotto'
      preLoaderRoute: typeof GamesLotteryLottoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/lottery/lotto/$round': {
      id: '/games/lottery/lotto/$round'
      path: '/games/lottery/lotto/$round'
      fullPath: '/games/lottery/lotto/$round'
      preLoaderRoute: typeof GamesLotteryLottoRoundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesLotteryLottoRoundRoute: GamesLotteryLottoRoundRoute,
  GamesLotteryLottoIndexRoute: GamesLotteryLottoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
